import type { Metadata } from "next";
import { Sarabun } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import AntdProvider from "@/components/provider/AntdProvider";
import Footer from "@/components/footer";

const sarabun = Sarabun({
  variable: "--font-sarabun",
  subsets: ["latin"],
  weight: "400"
})

const rubik = Sarabun({
  variable: "--font-rubik",
  subsets: ["latin"],
  weight: "400"
})

export const metadata: Metadata = {
  title: "Final Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sarabun.variable} ${rubik.className} w-screen h-screen flex flex-col antialiased`}>
        <AntdProvider>
          <Navbar/>
          <div className="pt-30">
            {children}
          </div>
          <Footer/>
        </AntdProvider>
      </body>
    </html>
  );
}
