import type { Metadata } from "next";
import { Sarabun } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import AntdProvider from "@/components/provider/AntdProvider";
import Footer from "@/components/footer";
import { Toaster } from "react-hot-toast";
import Loading from "@/components/loading";
import ProtectedRoute from "@/components/protectedroute";

const sarabun = Sarabun({
  variable: "--font-sarabun",
  subsets: ["latin"],
  weight: "400"
})

const rubik = Sarabun({
  variable: "--font-rubik",
  subsets: ["latin"],
  weight: "400"
})

export const metadata: Metadata = {
  title: "Final Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sarabun.variable} ${rubik.className} w-screen h-screen flex flex-col antialiased`}>
        <AntdProvider>
          <ProtectedRoute>
            <Navbar/>
            {children}
            <Footer/>
            <Toaster position="bottom-right"/>
            <Loading/>
          </ProtectedRoute>
        </AntdProvider>
      </body>
    </html>
  );
}
